version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build_linux: 
    docker:
      - image: circleci/node        
    steps:   
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "package-lock.json" }}
      - run: npm i 
      - save_cache:
          key: deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run prod

      - run: npm run build:linux
      - run: cp -r ./build/linux-unpacked/ ./build/app && rm -rf ./build/linux-unpacked/
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  publish:
    docker:
      - image: circleci/node
    steps:
      - attach_workspace:
          at: .
      - run: npm config set -- '//registry.npmjs.org/:_authToken=${npm_key}'
      - run: git config user.email "circleci@gorhumanslab.com"
      - run: git config user.name "Circle CI builder"
      - run: git config credential.helper 'cache --timeout=120'
      - run: npm version patch
      - run: npm publish --access public
      - run: git push -q https://${github_ci_token}@github.com/For-Humans-Lab/log-scope-app.git master --tags

workflows:
  build_and_publish_linux:
    when:
      and:
        - equal: [master, <<pipeline.git.branch>>]
        - <<pipeline.git.tag>>
    jobs:
      - build_linux
      - publish:
          requires:
            - build_linux
          context:
            main